#' Perform dimensionality reduction for proteomics data
#'
#' This function performs PCA and UMAP dimensionality reduction on proteomics data.
#' It handles normalized data from \code{proteo.normalize()}, ensures sample order matches
#' metadata, and replaces missing values with row means. Intra- and inter-group distances
#' are calculated on PC1 and PC2.
#'
#' @param normalized_data A data.frame or a list from \code{proteo.normalize()} containing
#'   normalized protein expression. Must have a ProteinID column.
#' @param n_neighbors Integer. Number of neighbors for UMAP. If NULL or larger than the number
#'   of samples, defaults to half the number of samples. Default is NULL.
#' @param verbose Logical. If TRUE (default), prints messages and summary statistics.
#' @param help Logical. If TRUE, prints this help message and example usage. Default = FALSE.
#'
#' @return A list containing:
#' \describe{
#'   \item{pca}{Result of \code{prcomp} PCA analysis.}
#'   \item{umap}{Result of \code{umap::umap} UMAP analysis.}
#'   \item{plot_pca}{ggplot2 PCA plot.}
#'   \item{plot_umap}{ggplot2 UMAP plot.}
#'   \item{n_neighbors}{Number of neighbors used in UMAP.}
#'   \item{dist_intra}{Mean intra-group distance (PC1 & PC2).}
#'   \item{dist_inter}{Mean inter-group distance (PC1 & PC2).}
#' }
#'
#' @examples
#'
#' proteins <- paste0("P", sprintf("%03d", 1:50))
#'
#' raw_data <- data.frame(
#'   ProteinID = proteins,
#'   Control_1   = rnorm(50, mean = 10000, sd = 2000),
#'   Control_2   = rnorm(50, mean = 10000, sd = 2000),
#'   Control_3   = rnorm(50, mean = 10000, sd = 2000),
#'   Control_4   = rnorm(50, mean = 10000, sd = 2000),
#'   Control_5   = rnorm(50, mean = 10000, sd = 2000),
#'   Treatment_1 = rnorm(50, mean = 20000, sd = 2500),
#'   Treatment_2 = rnorm(50, mean = 20000, sd = 2500),
#'   Treatment_3 = rnorm(50, mean = 20000, sd = 2500),
#'   Treatment_4 = rnorm(50, mean = 30000, sd = 2500),
#'   Treatment_5 = rnorm(50, mean = 30000, sd = 2500)
#' )
#'
#' metadata <- data.frame(
#'   Sample = colnames(raw_data)[-1],
#'   Group  = rep(c("Control", "Treatment"), each = 5)
#' )
#'
#' # Step 1: Normalize
#' normalized_obj <- proteo.normalize(raw_data, metadata, method = "none", verbose = FALSE)
#'
#' # Step 2: Perform dimensionality reduction
#' proteo.dimred(normalized_obj)
#'
#' @references
#' PCA: Pearson 1901 <doi:10.1080/14786440109462720>
#' UMAP: McInnes et al. 2020 <doi:10.21105/joss.02096>
#'
#' @export

proteo.dimred <- function(normalized_data,
                          n_neighbors = NULL,
                          verbose = TRUE,
                          help = FALSE) {

  if (help || missing(normalized_data)) {
    message("

Function proteo.dimred()

Description:
  Performs PCA and UMAP dimensionality reduction on proteomics data.
  Works directly with objects generated by proteo.normalize(), using
  the embedded metadata automatically.

Usage:
  proteo.dimred(normalized_data, n_neighbors = NULL, verbose = TRUE)
")
    return(invisible(NULL))
  }

  # --- Check required packages ---
  if (!requireNamespace("ggplot2", quietly = TRUE)) stop("Please install 'ggplot2'")
  if (!requireNamespace("umap", quietly = TRUE)) stop("Please install 'umap'")
  if (!requireNamespace("dplyr", quietly = TRUE)) stop("Please install 'dplyr'")

  # ================================
  # 1) Extract metadata automatically
  # ================================
  if (!is.list(normalized_data) || is.null(normalized_data$metadata)) {
    stop("normalized_data must be a proteoNorm object containing $metadata.")
  }

  metadata <- normalized_data$metadata

  # ================================
  # 2) Extract correct normalized matrix
  # ================================
  if (!is.null(normalized_data$normalized_matrix)) {
    normalized_matrix <- normalized_data$normalized_matrix
  } else {
    stop("normalized_data does not contain $normalized_matrix.")
  }

  # --- Detect ProteinID column ---
  possible_id_names <- c("ProteinID", "Protein_ID", "Protein", "Accession", "Protein.Accession", "protein_id")
  col_id <- which(names(normalized_matrix) %in% possible_id_names)
  if (length(col_id) != 1) stop("Unable to detect ProteinID column.")

  # --- Detect Sample and Group columns ---
  possible_sample_names <- c("Sample", "sample", "SAMPLE")
  col_sample <- which(names(metadata) %in% possible_sample_names)
  if (length(col_sample) != 1) stop("Unable to detect Sample column in metadata.")

  possible_group_names <- c("Group", "group", "GROUP", "Condition", "condition")
  col_group <- which(names(metadata) %in% possible_group_names)
  if (length(col_group) != 1) stop("Unable to detect Group column in metadata.")

  # --- Prepare expression matrix ---
  protein_names <- as.character(normalized_matrix[[col_id]])
  protein_names[is.na(protein_names) | protein_names == ""] <- "Protein_Unknown"
  protein_names <- make.unique(protein_names)

  expr_mat <- normalized_matrix[, -col_id, drop = FALSE]
  rownames(expr_mat) <- protein_names

  # --- Clean values ---
  expr_mat <- expr_mat[rowSums(!is.na(expr_mat)) > 1, , drop = FALSE]

  # Imputation
  expr_mat <- t(apply(expr_mat, 1, function(x) {
    if (all(is.na(x))) return(rep(NA, length(x)))
    x[is.na(x)] <- mean(x, na.rm = TRUE)
    x
  }))

  # --- Remove zero-variance rows BEFORE z-score ---
  zero_var_rows <- apply(expr_mat, 1, function(x) var(x, na.rm = TRUE) == 0)

  zero_ids <- rownames(expr_mat)[zero_var_rows]

  if (any(zero_var_rows)) {
    if (verbose) {
      warning(
        sprintf(
          "Rows with zero variance removed (%d): %s",
          length(zero_ids),
          paste(zero_ids, collapse = ", ")
        )
      )
    } else {
      warning(
        sprintf(
          "%d rows with zero variance were removed. Set verbose = TRUE to list IDs.",
          length(zero_ids)
        )
      )
    }
  }

  # Apply removal correctly here
  expr_mat <- expr_mat[!zero_var_rows, , drop = FALSE]

  # ================================
  # Apply z-score unless already normalized
  # ================================

  already_z <- !is.null(normalized_data$method) &&
    normalized_data$method %in% c("zscore", "Z-score", "z_score")

  if (!already_z) {
    if (verbose) message("Applying z-score scaling (per protein)...")

    expr_mat <- t(scale(t(expr_mat), center = TRUE, scale = TRUE))

    # Remove rows that become NA after scaling
    na_rows <- rowSums(is.na(expr_mat)) > 0
    if (any(na_rows)) {
      warning("Rows with NA after z-score removed: ",
              paste(rownames(expr_mat)[na_rows], collapse = ", "))
      expr_mat <- expr_mat[!na_rows, , drop = FALSE]
    }
  } else {
    if (verbose) message("Skipping z-score: normalization method already is z-score.")
  }

  # --- Match sample order ---
  samples <- metadata[[col_sample]]
  groups  <- metadata[[col_group]]

  expr_mat <- expr_mat[, samples, drop = FALSE]

  n_samples <- ncol(expr_mat)

  # --- Adjust n_neighbors ---
  if (is.null(n_neighbors) || n_neighbors >= n_samples) {
    n_neighbors <- max(2, floor(n_samples / 2))
    if (verbose) message(sprintf("n_neighbors for UMAP set to %d", n_neighbors))
  }

  # ================================
  # 3) PCA
  # ================================
  pca_res <- stats::prcomp(t(expr_mat), center = TRUE, scale. = TRUE)
  var_explained <- pca_res$sdev^2 / sum(pca_res$sdev^2)

  df_pca <- data.frame(
    PC1 = pca_res$x[,1],
    PC2 = pca_res$x[,2],
    Group = groups,
    Sample = samples
  )

  p_pca <- ggplot2::ggplot(df_pca, ggplot2::aes(x = PC1, y = PC2, color = Group)) +
    ggplot2::geom_point(size = 4, alpha = 0.8) +
    ggplot2::theme_minimal() +
    ggplot2::labs(title = "PCA - Dimensionality Reduction")

  # ================================
  # 4) UMAP
  # ================================
  umap_res <- umap::umap(t(expr_mat), n_neighbors = n_neighbors, init = "random")

  df_umap <- data.frame(
    UMAP1 = umap_res$layout[,1],
    UMAP2 = umap_res$layout[,2],
    Group = groups,
    Sample = samples
  )

  p_umap <- ggplot2::ggplot(df_umap, ggplot2::aes(x = UMAP1, y = UMAP2, color = Group)) +
    ggplot2::geom_point(size = 4, alpha = 0.8) +
    ggplot2::theme_minimal() +
    ggplot2::labs(title = "UMAP - Dimensionality Reduction")

  # ================================
  # Distances
  # ================================
  dist_mat <- as.matrix(stats::dist(df_pca[,c("PC1","PC2")]))

  intra <- c(); inter <- c()
  for (i in 1:(n_samples-1)) {
    for (j in (i+1):n_samples) {
      if (groups[i] == groups[j]) intra <- c(intra, dist_mat[i,j])
      else                       inter <- c(inter, dist_mat[i,j])
    }
  }

  if (verbose) {
    message("\n=== Dimensionality Reduction Report ===")
    message(sprintf("Variance explained PC1: %.1f%%", var_explained[1] * 100))
    message(sprintf("Variance explained PC2: %.1f%%", var_explained[2] * 100))
    message(sprintf("Mean intra-group distance: %.3f", mean(intra)))
    message(sprintf("Mean inter-group distance: %.3f", mean(inter)))
    message("========================================")
  }

  print(p_pca)
  print(p_umap)

  # ================================
  # Return
  # ================================

  invisible(list(
    pca = pca_res,
    umap = umap_res,
    plot_pca = p_pca,
    plot_umap = p_umap
  ))
}
